In [1]:
import tensorflow as tf

In [2]:
text_ds = tf.data.Dataset.list_files('reviews/*/*',shuffle=False)

for file in text_ds.take(3):
    print(file.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_1.txt'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_2.txt'>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_3.txt'>>


In [3]:
text_ds = text_ds.shuffle(200)

for file in text_ds.take(3):
    print(file.numpy())

b'reviews\\positive\\pos_3.txt'
b'reviews\\negative\\neg_1.txt'
b'reviews\\negative\\neg_2.txt'


In [4]:
class_names = ["Positive","Negative"]

In [5]:
text_count = len(text_ds)
text_count

6

In [9]:
import os
def extract_review_label(file_path):
    return tf.io.read_file(file_path), tf.strings.split(file_path, os.path.sep)[-2]

In [10]:
reviews_ds = text_ds.map(extract_review_label)
for review, label in reviews_ds:
    print("Review: ",review.numpy()[:50])
    print("Label: ",label.numpy())

Review:  b''
Label:  b'positive'
Review:  b'This show was an amazing, fresh & innovative idea '
Label:  b'negative'
Review:  b'One of the other reviewers has mentioned that afte'
Label:  b'positive'
Review:  b''
Label:  b'negative'
Review:  b'A wonderful little production. <br /><br />The fil'
Label:  b'positive'
Review:  b"Basically there's a family where a little boy (Jak"
Label:  b'negative'


In [11]:
reviews_ds_2 = reviews_ds.filter(lambda review, label: review!="")
for review, label in reviews_ds_2.as_numpy_iterator():
    print("Review: ",review[:50])
    print("Label: ",label)

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
Review:  b'This show was an amazing, fresh & innovative idea '
Label:  b'negative'
Review:  b"Basically there's a family where a little boy (Jak"
Label:  b'negative'
Review:  b'A wonderful little production. <br /><br />The fil'
Label:  b'positive'
Review:  b'One of the other reviewers has mentioned that afte'
Label:  b'positive'


4

2